[package]
name = "melos"
version = "0.1.0"
edition = "2025"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
midly = "0.5.3"
pest = "2.8.4"
pest_derive = "2.8.4"

[dev-dependencies]
pretty_assertions = "1.4.1"
